name: expense

services:
  frontend:
    image: docker.io/rkalluru/d79-frontend
    depends_on:
      - backend
    ports:
      - 80:80

  backend:
    image: docker.io/rkalluru/d79-backend
    depends_on:
      - mysql
      - schema
    ports:
      - 8080:8080
    environment:
      DB_HOST: "mysql"

  schema:
    image: docker.io/rkalluru/d79-schema-loader
    depends_on:
      - mysql
    environment:
      login_user: "root"
      login_password: "ExpenseApp@1"
      login_host: "mysql"
      app_repo: https://github.com/raghudevopsb79/expense-backend
      schema_file: /app/schema/backend.sql

  mysql:
    image: docker.io/mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "ExpenseApp@1"
    networks:
      - common

  sleep:
    image: docker.io/rkalluru/d79-schema-loader
    entrypoint: sleep 10000
    networks:
      - common

networks:
  common: